// <auto-generated />
using FireAlarm.Web.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FireAlarm.Web.Data.Migrations
{
    [DbContext(typeof(FireAlarmDbContext))]
    partial class FireAlarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.SensorDetails", b =>
                {
                    b.Property<int>("sensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("floorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sensorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sensorRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sensorStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sensorId");

                    b.ToTable("SensorDetails");
                });

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.SensorState", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("coLevel")
                        .HasColumnType("int");

                    b.Property<int>("sensorId")
                        .HasColumnType("int");

                    b.Property<int>("smokeLevel")
                        .HasColumnType("int");

                    b.HasKey("statusId");

                    b.HasIndex("sensorId");

                    b.ToTable("SensorState");
                });

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userMobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRoleId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("userRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("roleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.SensorState", b =>
                {
                    b.HasOne("FireAlarm.Web.Data.Entities.SensorDetails", "sensorDetails")
                        .WithMany("sensorStates")
                        .HasForeignKey("sensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FireAlarm.Web.Data.Entities.User", b =>
                {
                    b.HasOne("FireAlarm.Web.Data.Entities.UserRole", "userRole")
                        .WithMany("Users")
                        .HasForeignKey("userRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
